class Key
{
    constructor(keyCode)
    {
        this.keyCode = keyCode
        this.Down = false;
        this.Pressed = false;
        this.Released = false;
    }
}

class Keyboard {
    constructor() {}
    static Keys = {
        "Backspace": "backspace",
        "Tab": "tab",
        "Enter": "enter",
        "Shift_Right": "shift_right",
        "Shift_Left": "shift_left",
        "Ctrl_Left": "ctrl_left",
        "Ctrl_Right": "ctrl_right",
        "Alt_Left": "alt_left",
        "Alt_Right": "alt_right",
        "Pause": "pause",
        "Caps_Lock": "caps_lock",
        "Escape": "escape",
        "Space": "space",
        "Page_Up": "page_up",
        "Page_Down": "page_down",
        "End": "end",
        "Home": "home",
        "Left_Arrow": "arrow_left",
        "Up_Arrow": "arrow_up",
        "Right_Arrow": "arrow_right",
        "Down_Arrow": "arrow_down",
        "Print_Screen": "print_screen",
        "Insert": "insert",
        "Delete": "delete",
        "Zero": "0",
        "One": "1",
        "Two": "2",
        "Three": "3",
        "Four": "4",
        "Five": "5",
        "Six": "6",
        "Seven": "7",
        "Eight": "8",
        "Nine": "9",
        "A": "a",
        "B": "b",
        "C": "c",
        "D": "d",
        "E": "e",
        "F": "f",
        "G": "g",
        "H": "h",
        "I": "i",
        "J": "j",
        "K": "k",
        "L": "l",
        "M": "m",
        "N": "n",
        "O": "o",
        "P": "p",
        "Q": "q",
        "R": "r",
        "S": "s",
        "T": "t",
        "U": "u",
        "V": "v",
        "W": "w",
        "X": "x",
        "Y": "y",
        "Z": "z",
        "Meta_Left": "meta_left",
        "Meta_Right": "meta_right",
        "Select": "select",
        "Numpad_Zero": "numpad_0",
        "Numpad_One": "numpad_1",
        "Numpad_Two": "numpad_2",
        "Numpad_Three": "numpad_3",
        "Numpad_Four": "numpad_4",
        "Numpad_Five": "numpad_5",
        "Numpad_Six": "numpad_6",
        "Numpad_Seven": "numpad_7",
        "Numpad_Eight": "numpad_8",
        "Numpad_Nine": "numpad_9",
        "Numpad_Multiply": "numpad_multiply",
        "Numpad_Add": "numpad_add",
        "Numpad_Subtract": "numpad_subtract",
        "Numpad_Decimal": "numpad_decimal",
        "Numpad_Divide": "numpad_divide",
        "F1": "f1",
        "F2": "f2",
        "F3": "f3",
        "F4": "f4",
        "F5": "f5",
        "F6": "f6",
        "F7": "f7",
        "F8": "f8",
        "F9": "f9",
        "F10": "f10",
        "F11": "f11",
        "F12": "f12",
        "Num_Lock": "num_lock",
        "Scroll_Lock": "scroll_lock",
        "Semi_Colon": "semi_colon",
        "Equal_Sign": "equal_sign",
        "Comma": "comma",
        "Minus": "minus",
        "Period": "period",
        "Slash": "slash",
        "Backquote": "backquote",
        "Bracket_Left": "bracket_left",
        "Backslash": "backslash",
        "Braket_Right": "braket_right",
        "Quote": "quote"
    }
    static #Keys = {
        "backspace": new Key(8),
        "tab": new Key(9),
        "enter": new Key(13),
        "shift_left": new Key(16),
        "shift_right": new Key(16),
        "ctrl_left": new Key(17),
        "ctrl_right": new Key(17),
        "alt_left": new Key(18),
        "alt_right": new Key(18),
        "pause": new Key(19),
        "caps_lock": new Key(20),
        "escape": new Key(27),
        "space": new Key(32),
        "page_up": new Key(33),
        "page_down": new Key(34),
        "end": new Key(35),
        "home": new Key(36),
        "arrow_left": new Key(37),
        "arrow_up": new Key(38),
        "arrow_right": new Key(39),
        "arrow_down": new Key(40),
        "print_screen": new Key(44),
        "insert": new Key(45),
        "delete": new Key(46),
        "0": new Key(48),
        "1": new Key(49),
        "2": new Key(50),
        "3": new Key(51),
        "4": new Key(52),
        "5": new Key(53),
        "6": new Key(54),
        "7": new Key(55),
        "8": new Key(56),
        "9": new Key(57),
        "a": new Key(65),
        "b": new Key(66),
        "c": new Key(67),
        "d": new Key(68),
        "e": new Key(69),
        "f": new Key(70),
        "g": new Key(71),
        "h": new Key(72),
        "i": new Key(73),
        "j": new Key(74),
        "k": new Key(75),
        "l": new Key(76),
        "m": new Key(77),
        "n": new Key(78),
        "o": new Key(79),
        "p": new Key(80),
        "q": new Key(81),
        "r": new Key(82),
        "s": new Key(83),
        "t": new Key(84),
        "u": new Key(85),
        "v": new Key(86),
        "w": new Key(87),
        "x": new Key(88),
        "y": new Key(89),
        "z": new Key(90),
        "meta_left": new Key(91),
        "meta_right": new Key(92),
        "select": new Key(93),
        "numpad_0": new Key(96),
        "numpad_1": new Key(97),
        "numpad_2": new Key(98),
        "numpad_3": new Key(99),
        "numpad_4": new Key(100),
        "numpad_5": new Key(101),
        "numpad_6": new Key(102),
        "numpad_7": new Key(103),
        "numpad_8": new Key(104),
        "numpad_9": new Key(105),
        "numpad_multiply": new Key(106),
        "numpad_add": new Key(107),
        "numpad_subtract": new Key(109),
        "numpad_decimal": new Key(110),
        "numpad_divide": new Key(111),
        "f1": new Key(112),
        "f2": new Key(113),
        "f3": new Key(114),
        "f4": new Key(115),
        "f5": new Key(116),
        "f6": new Key(117),
        "f7": new Key(118),
        "f8": new Key(119),
        "f9": new Key(120),
        "f10": new Key(121),
        "f11": new Key(122),
        "f12": new Key(123),
        "num_lock": new Key(144),
        "scroll_lock": new Key(145),
        "semi_colon": new Key(186),
        "equal_sign": new Key(187),
        "comma": new Key(188),
        "minus": new Key(189),
        "period": new Key(190),
        "slash": new Key(191),
        "backquote": new Key(192),
        "bracket_left": new Key(219),
        "backslash": new Key(220),
        "braket_right": new Key(221),
        "quote": new Key(222)
    }
    static #CodeToKeys = {
        "Backspace": "backspace",
        "Tab": "tab",
        "Enter": "enter",
        "ShiftLeft": "shift_left",
        "ShiftRight": "shift_right",
        "ControlLeft": "ctrl_left",
        "ControlRight": "ctrl_right",
        "AltLeft": "alt_left",
        "AltRight": "alt_right",
        "Pause": "pause",
        "CapsLock": "caps_lock",
        "Escape": "escape",
        "Space": "space",
        "PageUp": "page_up",
        "PageDown": "page_down",
        "End": "end",
        "Home": "home",
        "ArrowLeft": "arrow_left",
        "ArrowUp": "arrow_up",
        "ArrowRight": "arrow_right",
        "ArrowDown": "arrow_down",
        "PrintScreen": "print_screen",
        "Insert": "insert",
        "Delete": "delete",
        "Digit0": "0",
        "Digit1": "1",
        "Digit2": "2",
        "Digit3": "3",
        "Digit4": "4",
        "Digit5": "5",
        "Digit6": "6",
        "Digit7": "7",
        "Digit8": "8",
        "Digit9": "9",
        "KeyA": "a",
        "KeyB": "b",
        "KeyC": "c",
        "KeyD": "d",
        "KeyE": "e",
        "KeyF": "f",
        "KeyG": "g",
        "KeyH": "h",
        "KeyI": "i",
        "KeyJ": "j",
        "KeyK": "k",
        "KeyL": "l",
        "KeyM": "m",
        "KeyN": "n",
        "KeyO": "o",
        "KeyP": "p",
        "KeyQ": "q",
        "KeyR": "r",
        "KeyS": "s",
        "KeyT": "t",
        "KeyU": "u",
        "KeyV": "v",
        "KeyW": "w",
        "KeyX": "x",
        "KeyY": "y",
        "KeyZ": "z",
        "MetaLeft": "meta_left",
        "MetaRight": "meta_right",
        "ContextMenu": "select",
        "Numpad0": "numpad_0",
        "Numpad1": "numpad_1",
        "Numpad2": "numpad_2",
        "Numpad3": "numpad_3",
        "Numpad4": "numpad_4",
        "Numpad5": "numpad_5",
        "Numpad6": "numpad_6",
        "Numpad7": "numpad_7",
        "Numpad8": "numpad_8",
        "Numpad9": "numpad_9",
        "NumpadMultiply": "numpad_multiply",
        "NumpadAdd": "numpad_add",
        "NumpadSubtract": "numpad_subtract",
        "NumpadDecimal": "numpad_decimal",
        "NumpadDivide": "numpad_divide",
        "F1": "f1",
        "F2": "f2",
        "F3": "f3",
        "F4": "f4",
        "F5": "f5",
        "F6": "f6",
        "F7": "f7",
        "F8": "f8",
        "F9": "f9",
        "F10": "f10",
        "F11": "f11",
        "F12": "f12",
        "NumLock": "num_lock",
        "ScrollLock": "scroll_lock",
        "Semicolon": "semi_colon",
        "Equal": "equal_sign",
        "Comma": "comma",
        "Minus": "minus",
        "Period": "period",
        "Slash": "slash",
        "Backquote": "backquote",
        "BracketLeft": "bracket_left",
        "Backslash": "backslash",
        "BracketRight": "braket_right",
        "Quot": "quote"
    }
    static #Pressed = [];
    static Event(e)
    {
        var key_state = (e.type === "keydown");
        var key = Keyboard.#Keys[Keyboard.#CodeToKeys[e.code]];
        if(!key.Down)
          key.Pressed = key_state;
        key.Released = !key_state;
        key.Down = key_state;
        Keyboard.#Pressed.push(key);
    }
    static get pressed()
    {
        console.log(Keyboard.#Pressed);
    }
    static Update()
    {
        for(var key = Keyboard.#Pressed.length - 1; key >= 0; key--)
        {
            Keyboard.#Pressed[key].Pressed = false;
            Keyboard.#Pressed[key].Released = false;
            Keyboard.#Pressed.splice(key, 1);
        }
    }

    static KeyState(key)
    {
        return Keyboard.#Keys[key]
    }
}
document.addEventListener("keydown", Keyboard.Event);
document.addEventListener("keyup", Keyboard.Event);